"""
deploy_to_snowflake.py
======================
Concatenates all CHI Reporting views into a single deployable SQL file.

Usage:
    uv run python deploy_to_snowflake.py [--year 2025] [--output deploy.sql]

    If --output is omitted, prints to stdout (can pipe to SnowSQL).

Example:
    uv run python deploy_to_snowflake.py --year 2025 --output chi_reporting_2025.sql
"""

import os, sys

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
QUERIES_DIR = os.path.join(BASE_DIR, "project_queries")

# Deployment order: config first, then each condition: staging → analytical → reports
DEPLOY_ORDER = [
    ("00_CONFIG",               os.path.join(QUERIES_DIR, "00_config.sql")),
    ("01_DM_Staging",           os.path.join(QUERIES_DIR, "Diabetes", "dm_staging_views.sql")),
    ("02_DM_Analytical",        os.path.join(QUERIES_DIR, "Diabetes", "dm_analytical_view.sql")),
    ("03_DM_Reports",           os.path.join(QUERIES_DIR, "Diabetes", "dm_report_views.sql")),
    ("04_HTN_Staging",          os.path.join(QUERIES_DIR, "HTN", "htn_staging_views.sql")),
    ("05_HTN_Analytical",       os.path.join(QUERIES_DIR, "HTN", "htn_analytical_view.sql")),
    ("06_HTN_Reports",          os.path.join(QUERIES_DIR, "HTN", "htn_report_views.sql")),
    ("07_DLP_Staging",          os.path.join(QUERIES_DIR, "DLP", "dlp_staging_views.sql")),
    ("08_DLP_Analytical",       os.path.join(QUERIES_DIR, "DLP", "dlp_analytical_view.sql")),
    ("09_DLP_Reports",          os.path.join(QUERIES_DIR, "DLP", "dlp_report_views.sql")),
    ("10_OB_Staging",           os.path.join(QUERIES_DIR, "OBS", "ob_staging_views.sql")),
    ("11_OB_Analytical",        os.path.join(QUERIES_DIR, "OBS", "ob_analytical_view.sql")),
    ("12_OB_Reports",           os.path.join(QUERIES_DIR, "OBS", "ob_report_views.sql")),
    ("13_DM_Monitoring",        os.path.join(QUERIES_DIR, "Diabetes", "dm_monitoring_views.sql")),
    ("14_HTN_Monitoring",       os.path.join(QUERIES_DIR, "HTN", "htn_monitoring_views.sql")),
    ("15_DLP_Monitoring",       os.path.join(QUERIES_DIR, "DLP", "dlp_monitoring_views.sql")),
    ("16_OB_Monitoring",        os.path.join(QUERIES_DIR, "OBS", "ob_monitoring_views.sql")),
]


def build_sql(year):
    """Concatenate all SQL files into a single deployable script."""
    lines = []
    lines.append("-- ============================================================================")
    lines.append(f"-- CHI REPORTING — Complete Deployment (Report Year: {year})")
    lines.append("-- ============================================================================")
    lines.append("-- Generated by deploy_to_snowflake.py")
    lines.append("--")
    lines.append("-- Run this entire file in your Snowflake worksheet or via SnowSQL:")
    lines.append("--   snowsql -f chi_reporting_deploy.sql")
    lines.append("--")
    lines.append("-- DEPLOYMENT ORDER:")
    lines.append("--   1. Config (schema + year + thresholds)")
    lines.append("--   2. DM  — Staging → Analytical → Reports → Monitoring")
    lines.append("--   3. HTN — Staging → Analytical → Reports → Monitoring")
    lines.append("--   4. DLP — Staging → Analytical → Reports → Monitoring")
    lines.append("--   5. OB  — Staging → Analytical → Reports → Monitoring")
    lines.append("-- ============================================================================")
    lines.append("")

    for i, (label, path) in enumerate(DEPLOY_ORDER):
        lines.append("")
        lines.append(f"-- {'=' * 70}")
        lines.append(f"-- STEP {i + 1}/17: {label}")
        lines.append(f"-- {'=' * 70}")
        lines.append("")

        try:
            with open(path, "r", encoding="utf-8") as f:
                sql = f.read()

            # Replace year if different from default
            if year != 2025:
                sql = sql.replace("2025-01-01", f"{year}-01-01")
                sql = sql.replace("2026-01-01", f"{year + 1}-01-01")

            lines.append(sql)
            lines.append("")
        except FileNotFoundError:
            lines.append(f"-- [WARNING] File not found: {path}")
            lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    year = 2025
    output_file = None

    args = sys.argv[1:]
    i = 0
    while i < len(args):
        if args[i] == "--year" and i + 1 < len(args):
            year = int(args[i + 1])
            i += 2
        elif args[i] == "--output" and i + 1 < len(args):
            output_file = args[i + 1]
            i += 2
        else:
            i += 1

    sql = build_sql(year)

    if output_file:
        with open(output_file, "w", encoding="utf-8") as f:
            f.write(sql)
        print(f"[OK] Deploy SQL written to: {output_file}")
        print(f"  Report year: {year}")
        print(f"  33 views across 4 conditions (DM, HTN, DLP, OB) incl. compliance & care gap")
        print(f"\n  Deploy in Snowflake:")
        print(f"    snowsql -f {output_file}")
        print(f"  Or copy-paste into a Snowflake worksheet.")
    else:
        print(sql)
